/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'tutorial',
      label: 'Tutorial',
    },
    {
      type: 'category',
      label: 'Micro-Controladores',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'STM32',
          collapsed: false,
          items: [
            'micro-controladores/STM32/stm32_cdc_develop'
          ]
        },
        {
            type: 'category',
            label: 'ESP32',
            collapsed: false,
            items: [
              {
                type: 'link',
                label: ' ',
                href: '#'
              },
              'micro-controladores/ESP32/esp32-mcpwm-usage-and-examples',
              'micro-controladores/ESP32/esp32-rf24-demo'
            ]
        },
        {
            type: 'category',
            label: 'RP2040',
            collapsed: false,
            items: [
              {
                type: 'link',
                label: ' ',
                href: '#'
              },
              'micro-controladores/RP2040/rp2040-uart-interrupt-handling-and-usage',
              'micro-controladores/RP2040/rp2040-pwm-usage-and-examples',
              'micro-controladores/RP2040/rp2040-timer-and-alarm-usage',
              'micro-controladores/RP2040/mastering-pio-programming',
              'micro-controladores/RP2040/pio-uart-implementation',
              'micro-controladores/RP2040/advanced-pio-led-control-and-resource-management',
              'micro-controladores/RP2040/rp2040-rf24-demo'
            ]
        }
      ]
    }
  ]
   
};

export default sidebars;
