name: Deploy

on:
  push:
    branches:
      - v3.0
      
    paths-ignore:
      - "ISSUE_TEMPLATE/**"
      - ".github/**.md"
      - ".gitignore"
      - "demo/**"
      - "docker/**"
      - "HOW_TO.md"
      - "TASK.md"
      - "SECURITY.md"
      - "README.md"
      - "README_zh-CN.md"
      
  schedule:
    #UTC 0 
    - cron: '0 0 * * *'

jobs:
  lint:
    name: test_ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Checkout
        uses: actions/checkout@master
        
      - name: INSTALL SSH KEY
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PC }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: GIT CLONE
        run: |
            sudo apt-get update
            sudo apt-get install \
                  git -y 
            git config --global user.name 'tianrking'
            git config --global user.email 'tian.r.king@gmail.com'
            git clone git@github.com:tianrking/tianrking.github.io.git ~/docusaurus_wiki
            
      - name: NPM RUN for HTML BUILD
        run: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            cd  ~/docusaurus_wiki
            sudo apt remove cmdtest
            sudo apt update && sudo apt install yarn
            yarn add docusaurus
            yarn add @docusaurus/theme-mermaid
            yarn add remark-math@3 rehype-katex@4
            yarn add @docusaurus/theme-search-algolia
            yarn add remark-math@3 rehype-katex@5 hast-util-is-element@1.1.0
            yarn add @docusaurus/plugin-content-docs
            yarn add @docusaurus/plugin-debug
            yarn add @docusaurus/plugin-pwa
            yarn add --dev @docusaurus/eslint-plugin
            yarn add @docusaurus/theme-live-codeblock
            yarn build
      
      - name: PUBLISH to WEBSITE
        run: |
            cd  ~/docusaurus_wiki/build
            git init
            git remote add github git@github.com:tianrking/tianrking.github.io.git
            git checkout -b v3.0_HTML
            git add .
            git commit -m "Update"
            git push -u github HTML -f





          
